name: Automated Tests | frontend/

on:
  push:
    branches: [ main, dev/main ]
  pull_request:
    branches: [ main, dev/main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests/
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn test
